baseURL = "https://adamofsound.github.io/motorsport-news/"
languageCode = "en-us"
title = "Motorsport Pulse"
theme = "PaperMod"
publishDir = "docs"

[params]
  author = "Your Name"
  description = "Latest F1, WEC & IMSA news, analysis & media"
  showReadingTime = false
  disableAssetFingerprinting = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
[params.assets]
  customJS = ["js/ads.js"]